# Site settings
title: Dr. Y.P. Pant Foundation
description: Dr. Yadav rasad Research And Developmment Foundation
  
# Contact information
street_address: kalikasthan
city: Kathmandu
state:
zip_code: 46400
country: Nepal
name: 
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
500px:
  url:
  label:
facebook:
  url: https://github.com/apehex
  label:
github:
  url: https://github.com/apehex
  label:
gitlab:
  url:
  label:
instagram:
  url: https://github.com/apehex
  label:
linkedin:
  url:
  label:
medium:
  url: https://github.com/apehex
  label:
pinterest:
  url:
  label:
slack:
  url:
  label:
snapchat:
  url: https://github.com/apehex
  label:
twitter:
  url: https://github.com/apehex
  label:

# Optional elements
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
legal_terms:
  url: /en/legal-terms/
privacy_policy:
  url: /en/privacy-policy/
  third_party:
    hosting: github

# Recaptcha in forms
recaptcha:
  sitekey: 6LfMccgUAAAAAJcASCBTwXpeEXw7qjC-KkqjpsYV
  secretkey: 6LfMccgUAAAAAEYb9GfycbY2FQR_EcEypQFG1_32

# Collections
collections:
  redirects:
    output: true
    permalink: /:path/

# Default settings
defaults:
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
      lang: "x-default"
  -
    scope:
      path: ""
    values:
      menu: default
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"

# Build settings
permalink: pretty
markdown: kramdown
sass:
  sourcemap: never
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. http://example.com
author: Apehex
copyright:
  holder: Untitled
  license: CC0 BY-NC-SA

# Exclude from processing
